### ISSUE TITLE
JupyterComplete issue

### ISSUE THREAD

**Issue by lkhphuc** [lkhphuc/jupyter-kernel.nvim#3]
Hi @kiyoon @WhiteBlackGoose l I started a new issue since the last one is quite long.

Autocompletion with nvim-cmp is a bit finicky in my experience too, but it does not seem to be the kernel not responding but nvim-cmp decides to not show it up.

Just to be sure, after attaching, can you insert a new line with "%{cursor}" and then manually trigger nvim-cmp complete (`<C-Space>` for me)? If the server is responding you should see some magic command from the kernel.
![Screenshot 2023-02-26 at 10 16 34](https://user-images.githubusercontent.com/12573521/221404621-01d658c4-0dce-40f1-a152-c70adbe99cbc.png)

In my case, if I remove all cmp's sources and only use "jupyter", it works almost instantly just like with LSP, but with LSP enabled, results from LSP usually "drown out" jupyter results, make none of them shown up.

![Screenshot 2023-02-26 at 10 42 31](https://user-images.githubusercontent.com/12573521/221405659-cf6277eb-9dd4-4bea-a171-3aa9f018398b.png)

**Comment by kiyoon** [comment]
![image](https://user-images.githubusercontent.com/12980409/221406096-d9a27f85-9114-4815-a2ed-b9bbfc3ba3df.png)
It seems to be not showing up still

**Comment by lkhphuc** [comment]
Can you try install from this branch https://github.com/lkhphuc/jupyter-kernel.nvim/tree/cmp ?

I add some debug log inside python code and lua code? Can you copy that for me from `:message` output? I am afraid I won't be able to do anything without seeing the actual response.

**Comment by WhiteBlackGoose** [comment]
Works for me after I figured out, how to use nvim-cmp. Thank you so much! Gonna use your plugin right away

**Comment by kiyoon** [comment]
![image](https://user-images.githubusercontent.com/12980409/221411627-e11ca66f-687d-4294-bc87-0122de3d5436.png)

**Comment by kiyoon** [comment]
```
:messages
Jupyter kernel completion timeout
"CMP call: "
vim.empty_dict()
Jupyter complete: {'matches': [], 'cursor_end': 7, 'cursor_start': 7, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
Jupyter complete: {'matches': [], 'cursor_end': 6, 'cursor_start': 6, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
Jupyter complete: {'matches': [], 'cursor_end': 5, 'cursor_start': 5, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
Jupyter complete: {'matches': [], 'cursor_end': 4, 'cursor_start': 4, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
Jupyter complete: {'matches': ['csv'], 'cursor_end': 3, 'cursor_start': 0, 'metadata': {'_jupyter_types_experimental': [{'start': 0, 'e
nd': 3, 'text': 'csv', 'type': 'instance'}]}, 'status': 'ok'}
Jupyter kernel's exception: 'signature'
"CMP call: "
vim.empty_dict()
Jupyter complete: {'matches': [], 'cursor_end': 7, 'cursor_start': 7, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
Jupyter complete: {'matches': [], 'cursor_end': 6, 'cursor_start': 6, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
Jupyter complete: {'matches': [], 'cursor_end': 5, 'cursor_start': 5, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
Jupyter complete: {'matches': [], 'cursor_end': 4, 'cursor_start': 4, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
Jupyter complete: {'matches': ['csv'], 'cursor_end': 3, 'cursor_start': 0, 'metadata': {'_jupyter_types_experimental': [{'start': 0, 'e
nd': 3, 'text': 'csv', 'type': 'instance'}]}, 'status': 'ok'}
Jupyter kernel's exception: 'signature'
"CMP call: "
vim.empty_dict()
Jupyter complete: {'matches': [], 'cursor_end': 7, 'cursor_start': 7, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
Jupyter complete: {'matches': [], 'cursor_end': 6, 'cursor_start': 6, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
Jupyter complete: {'matches': [], 'cursor_end': 5, 'cursor_start': 5, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
Jupyter complete: {'matches': [], 'cursor_end': 4, 'cursor_start': 4, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
Jupyter complete: {'matches': ['csv'], 'cursor_end': 3, 'cursor_start': 0, 'metadata': {'_jupyter_types_experimental': [{'start': 0, 'e
nd': 3, 'text': 'csv', 'type': 'instance'}]}, 'status': 'ok'}
Jupyter kernel's exception: 'signature'
"CMP call: "
vim.empty_dict()
Jupyter complete: {'matches': [], 'cursor_end': 5, 'cursor_start': 5, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
Jupyter complete: {'matches': [], 'cursor_end': 5, 'cursor_start': 5, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
Jupyter complete: {'matches': ['callable', 'chr', 'class', 'classmethod', 'compile', 'complex', 'continue', 'copyright', 'credits', 'cs
v', '%%capture', '%cat', '%cd', '%clear', '%colors', '%conda', '%config', '%connect_info', 'core-js-banners', '%cp'], 'cursor_end': 1,
'cursor_start': 0, 'metadata': {'_jupyter_types_experimental': [{'start': 0, 'end': 1, 'text': 'callable', 'type': 'function'}, {'start
': 0, 'end': 1, 'text': 'chr', 'type': 'function'}, {'start': 0, 'end': 1, 'text': 'class', 'type': 'keyword'}, {'start': 0, 'end': 1,
'text': 'classmethod', 'type': 'class'}, {'start': 0, 'end': 1, 'text': 'compile', 'type': 'function'}, {'start': 0, 'end': 1, 'text':
'complex', 'type': 'class'}, {'start': 0, 'end': 1, 'text': 'continue', 'type': 'keyword'}, {'start': 0, 'end': 1, 'text': 'copyright',
 'type': 'function'}, {'start': 0, 'end': 1, 'text': 'credits', 'type': 'function'}, {'start': 0, 'end': 1, 'text': 'csv', 'type': 'ins
tance'}, {'start': 0, 'end': 1, 'text': '%%capture', 'type': '<unknown>'}, {'start': 0, 'end': 1, 'text': '%cat', 'type': '<unknown>'},
 {'start': 0, 'end': 1, 'text': '%cd', 'type': '<unknown>'}, {'start': 0, 'end': 1, 'text': '%clear', 'type': '<unknown>'}, {'start': 0
, 'end': 1, 'text': '%colors', 'type': '<unknown>'}, {'start': 0, 'end': 1, 'text': '%conda', 'type': '<unknown>'}, {'start': 0, 'end':
 1, 'text': '%config', 'type': '<unknown>'}, {'start': 0, 'end': 1, 'text': '%connect_info', 'type': '<unknown>'}, {'start': 0, 'end':
1, 'text': 'core-js-banners', 'type': '<unknown>'}, {'start': 0, 'end': 1, 'text': '%cp', 'type': '<unknown>'}]}, 'status': 'ok'}
Jupyter kernel's exception: 'signature'
"CMP call: "
vim.empty_dict()
Jupyter complete: {'matches': ['csv'], 'cursor_end': 2, 'cursor_start': 0, 'metadata': {'_jupyter_types_experimental': [{'start': 0, 'e
nd': 2, 'text': 'csv', 'type': 'instance'}]}, 'status': 'ok'}
Jupyter kernel's exception: 'signature'
"CMP call: "
vim.empty_dict()
Jupyter complete: {'matches': ['csv'], 'cursor_end': 3, 'cursor_start': 0, 'metadata': {'_jupyter_types_experimental': [{'start': 0, 'e
nd': 3, 'text': 'csv', 'type': 'instance'}]}, 'status': 'ok'}
Jupyter kernel's exception: 'signature'
"CMP call: "
vim.empty_dict()
Jupyter complete: {'matches': ['csv'], 'cursor_end': 3, 'cursor_start': 0, 'metadata': {'_jupyter_types_experimental': [{'start': 0, 'e
nd': 3, 'text': 'csv', 'type': 'instance'}]}, 'status': 'ok'}
Jupyter kernel's exception: 'signature'
"CMP call: "
vim.empty_dict()

```

**Comment by lkhphuc** [comment]
Thank you very much. Can you pull that branch again?

Interesting your jupyter_experimental does not have 'signature' field, while mine default to 'signature' with empty string. I pushed some minor change to handle access dict item with default, which I should do in the first place.

~Another aspect which your log show clearly is that not every "Jupyter complete" called from Python is followed by a "CMP complete" called from lua. This is the finicky behaviour I was refering to when using both "jupyter" and "cmp-lsp" sources. I need to get understand more about nvim-cmp to fix that.~ Not true.

**Comment by kiyoon** [comment]
I still don't see completions but I get better logs I think.

```
"a.ju.py" 13L, 110B written
Jupyter kernel completion timeout
"CMP call: "
vim.empty_dict()
Jupyter complete: {'matches': ['csv'], 'cursor_end': 3, 'cursor_start': 1, 'metadata': {'_jupyter_types_experimental': [{'start': 1, 'e
nd': 3, 'text': 'csv', 'type': 'instance'}]}, 'status': 'ok'}
"CMP call: "
{ {
    documentation = {
      kind = "markdown",
      value = "```python\n\n```"
    },
    kind = 6,
    label = "csv"
  } }
Jupyter complete: {'matches': ['%callable', '%chr', '%classmethod', '%compile', '%complex', '%copyright', '%credits', '%csv', '%%captur
e', '%cat', '%cd', '%clear', '%colors', '%conda', '%config', '%connect_info', '%cp'], 'cursor_end': 2, 'cursor_start': 0, 'metadata': {
'_jupyter_types_experimental': [{'start': 0, 'end': 2, 'text': '%callable', 'type': 'function'}, {'start': 0, 'end': 2, 'text': '%chr',
 'type': 'function'}, {'start': 0, 'end': 2, 'text': '%classmethod', 'type': 'class'}, {'start': 0, 'end': 2, 'text': '%compile', 'type
': 'function'}, {'start': 0, 'end': 2, 'text': '%complex', 'type': 'class'}, {'start': 0, 'end': 2, 'text': '%copyright', 'type': 'func
tion'}, {'start': 0, 'end': 2, 'text': '%credits', 'type': 'function'}, {'start': 0, 'end': 2, 'text': '%csv', 'type': 'instance'}, {'s
tart': 0, 'end': 2, 'text': '%%capture', 'type': '<unknown>'}, {'start': 0, 'end': 2, 'text': '%cat', 'type': '<unknown>'}, {'start': 0
, 'end': 2, 'text': '%cd', 'type': '<unknown>'}, {'start': 0, 'end': 2, 'text': '%clear', 'type': '<unknown>'}, {'start': 0, 'end': 2,
'text': '%colors', 'type': '<unknown>'}, {'start': 0, 'end': 2, 'text': '%conda', 'type': '<unknown>'}, {'start': 0, 'end': 2, 'text':
'%config', 'type': '<unknown>'}, {'start': 0, 'end': 2, 'text': '%connect_info', 'type': '<unknown>'}, {'start': 0, 'end': 2, 'text': '
%cp', 'type': '<unknown>'}]}, 'status': 'ok'}
Jupyter kernel's exception: '<unknown>'
"CMP call: "
vim.empty_dict()
Jupyter complete: {'matches': ['callable', 'chr', 'class', 'classmethod', 'compile', 'complex', 'continue', 'copyright', 'credits', 'cs
v', '%%capture', '%cat', '%cd', '%clear', '%colors', '%conda', '%config', '%connect_info', 'core-js-banners', '%cp'], 'cursor_end': 1,
'cursor_start': 0, 'metadata': {'_jupyter_types_experimental': [{'start': 0, 'end': 1, 'text': 'callable', 'type': 'function'}, {'start
': 0, 'end': 1, 'text': 'chr', 'type': 'function'}, {'start': 0, 'end': 1, 'text': 'class', 'type': 'keyword'}, {'start': 0, 'end': 1,
'text': 'classmethod', 'type': 'class'}, {'start': 0, 'end': 1, 'text': 'compile', 'type': 'function'}, {'start': 0, 'end': 1, 'text':
'complex', 'type': 'class'}, {'start': 0, 'end': 1, 'text': 'continue', 'type': 'keyword'}, {'start': 0, 'end': 1, 'text': 'copyright',
 'type': 'function'}, {'start': 0, 'end': 1, 'text': 'credits', 'type': 'function'}, {'start': 0, 'end': 1, 'text': 'csv', 'type': 'ins
tance'}, {'start': 0, 'end': 1, 'text': '%%capture', 'type': '<unknown>'}, {'start': 0, 'end': 1, 'text': '%cat', 'type': '<unknown>'},
 {'start': 0, 'end': 1, 'text': '%cd', 'type': '<unknown>'}, {'start': 0, 'end': 1, 'text': '%clear', 'type': '<unknown>'}, {'start': 0
, 'end': 1, 'text': '%colors', 'type': '<unknown>'}, {'start': 0, 'end': 1, 'text': '%conda', 'type': '<unknown>'}, {'start': 0, 'end':
 1, 'text': '%config', 'type': '<unknown>'}, {'start': 0, 'end': 1, 'text': '%connect_info', 'type': '<unknown>'}, {'start': 0, 'end':
1, 'text': 'core-js-banners', 'type': '<unknown>'}, {'start': 0, 'end': 1, 'text': '%cp', 'type': '<unknown>'}]}, 'status': 'ok'}
Jupyter kernel's exception: '<unknown>'
"CMP call: "
vim.empty_dict()
Jupyter complete: {'matches': ['csv'], 'cursor_end': 2, 'cursor_start': 0, 'metadata': {'_jupyter_types_experimental': [{'start': 0, 'e
nd': 2, 'text': 'csv', 'type': 'instance'}]}, 'status': 'ok'}
"CMP call: "
{ {
    documentation = {
      kind = "markdown",
      value = "```python\n\n```"
    },
    kind = 6,
    label = "csv"
  } }
Jupyter complete: {'matches': ['csv'], 'cursor_end': 3, 'cursor_start': 0, 'metadata': {'_jupyter_types_experimental': [{'start': 0, 'e
nd': 3, 'text': 'csv', 'type': 'instance'}]}, 'status': 'ok'}
"CMP call: "
{ {
    documentation = {
      kind = "markdown",
      value = "```python\n\n```"
    },
    kind = 6,
    label = "csv"
  } }
Jupyter complete: {'matches': ['csv'], 'cursor_end': 3, 'cursor_start': 0, 'metadata': {'_jupyter_types_experimental': [{'start': 0, 'e
nd': 3, 'text': 'csv', 'type': 'instance'}]}, 'status': 'ok'}
"CMP call: "
{ {
    documentation = {
      kind = "markdown",
      value = "```python\n\n```"
    },
    kind = 6,
    label = "csv"
  } }
Jupyter complete: {'matches': ['csv'], 'cursor_end': 3, 'cursor_start': 0, 'metadata': {'_jupyter_types_experimental': [{'start': 0, 'e
nd': 3, 'text': 'csv', 'type': 'instance'}]}, 'status': 'ok'}
"CMP call: "
{ {
    documentation = {
      kind = "markdown",
      value = "```python\n\n```"
    },
    kind = 6,
    label = "csv"
  } }
```

**Comment by kiyoon** [comment]
![image](https://user-images.githubusercontent.com/12980409/221416912-8469b5da-5ee1-4958-95be-e08026438c78.png)

**Comment by lkhphuc** [comment]
Apart from some `Jupyter kernel's exception: '<unknown>'` which was thrown by the kernel and I cannot fix,
From these log alone, cmp should popup with offer to complete to "csv" instance, possibly while you are typing `c` or `cs`:
```
"CMP call: "
{ {
    documentation = {
      kind = "markdown",
      value = "```python\n\n```"
    },
    kind = 6,
    label = "csv"
  } }
```

Can you try remove all sources from cmp except for `jupyter`, execute `import numpy as np` and try completing on something like `np.arr`? With only jupyter source it give me instant results just like with LSP.

**Comment by kiyoon** [comment]
I think the csv and np works. But the `%`, `csv.` and `np.arr` doesn't really work.

```
Jupyter complete: {'matches': ['next', 'nonlocal', 'not', 'np', '%notebook', 'nvim-coc.kiyoon/', 'nvim.kiyoon/'], 'cursor_end': 1, 'cur
sor_start': 0, 'metadata': {'_jupyter_types_experimental': [{'start': 0, 'end': 1, 'text': 'next', 'type': 'function'}, {'start': 0, 'e
nd': 1, 'text': 'nonlocal', 'type': 'keyword'}, {'start': 0, 'end': 1, 'text': 'not', 'type': 'keyword'}, {'start': 0, 'end': 1, 'text'
: 'np', 'type': 'module'}, {'start': 0, 'end': 1, 'text': '%notebook', 'type': '<unknown>'}, {'start': 0, 'end': 1, 'text': 'nvim-coc.k
iyoon/', 'type': '<unknown>'}, {'start': 0, 'end': 1, 'text': 'nvim.kiyoon/', 'type': '<unknown>'}]}, 'status': 'ok'}
Jupyter kernel's exception: '<unknown>'
"CMP call: "
vim.empty_dict()
Jupyter complete: {'matches': ['np'], 'cursor_end': 2, 'cursor_start': 0, 'metadata': {'_jupyter_types_experimental': [{'start': 0, 'en
d': 2, 'text': 'np', 'type': 'module'}]}, 'status': 'ok'}
"CMP call: "
{ {
    documentation = {
      kind = "markdown",
      value = "```python\n\n```"
    },
    kind = 9,
    label = "np"
  } }
Jupyter complete: {'matches': [], 'cursor_end': 4, 'cursor_start': 4, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
Jupyter complete: {'matches': [], 'cursor_end': 5, 'cursor_start': 5, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
Jupyter complete: {'matches': [], 'cursor_end': 6, 'cursor_start': 6, 'metadata': {'_jupyter_types_experimental': []}, 'status': 'ok'}
"CMP call: "
{}
```

This may be related to `%`?
```
Jupyter complete: {'matches': ['as', 'a.ipynb', 'a.ju.py', '%alias', '%alias_magic', '%autoawait', '%autocall', '%automagic', '%autosav
e'], 'cursor_end': 14, 'cursor_start': 13, 'metadata': {'_jupyter_types_experimental': [{'start': 13, 'end': 14, 'text': 'as', 'type':
'keyword'}, {'start': 13, 'end': 14, 'text': 'a.ipynb', 'type': '<unknown>'}, {'start': 13, 'end': 14, 'text': 'a.ju.py', 'type': '<unk
nown>'}, {'start': 13, 'end': 14, 'text': '%alias', 'type': '<unknown>'}, {'start': 13, 'end': 14, 'text': '%alias_magic', 'type': '<un
known>'}, {'start': 13, 'end': 14, 'text': '%autoawait', 'type': '<unknown>'}, {'start': 13, 'end': 14, 'text': '%autocall', 'type': '<
unknown>'}, {'start': 13, 'end': 14, 'text': '%automagic', 'type': '<unknown>'}, {'start': 13, 'end': 14, 'text': '%autosave', 'type':
'<unknown>'}]}, 'status': 'ok'}
Jupyter kernel's exception: '<unknown>'
"CMP call: "
vim.empty_dict()
Jupyter complete: {'matches': ['as'], 'cursor_end': 15, 'cursor_start': 13, 'metadata': {'_jupyter_types_experimental': [{'start': 13,
'end': 15, 'text': 'as', 'type': 'keyword'}]}, 'status': 'ok'}
"CMP call: "
{ {
    documentation = {
      kind = "markdown",
      value = "```python\n\n```"
    },
    kind = 14,
    label = "as"
  } }
```

**Comment by lkhphuc** [comment]
Good to know that it at least work in some case. For the remaining issues:

- `Jupyter kernel's exception: '<unknown>'`. I already print out the exception using string format but if unknown is all we have than there's nothing can be done really. If you known anyway to get out of this exception than "unknown" please let me know.

- > But the %, csv. and np.arr doesn't really work.

I suppose this is the behaviour when using together with cmp-lsp source? Is that correct in your case? In my case I have to toggle on and off cmp a few times at `np.arr` for jupyter source to show up. If so then you have full feature-parity with me now.

If 'jupyter' is the only source then it work instantly though. I have to dig deeper into nvim-cmp to make lsp and jupyter work nicer together.

**Comment by kiyoon** [comment]
I turned off everything except jupyter, but still didn't get the completion. I guess it's more complicated than it looks like

**Comment by kiyoon** [comment]
I think you need to add trigger character for nvim-cmp

**Comment by kiyoon** [comment]
I've ported the functionalities to my jupyter plugin. Looking at the log, it seems like depending on the kernel I choose it only shows completion partially and not inside a variable scope, because the kernel just crashes getting the response. It just looks like a dependency issue with Jupyter and I'm not going to worry about it. I think you should merge the PR and consider adding trigger character like `"` and `%` etc.

Thanks a lot for your work, since Jupyter has really poor documentation I didn't know such functionality (especially completion) exists out of the box. It was a really useful inspiration and I'll keep an eye on your work.

**Comment by lkhphuc** [comment]
Cheers. I will take a look at your cmp implementation and copied back here as well. I will add link to your plugin to the readme if anyone is looking for a well-rounded notebook experience. Thanks.
